app:
  name: "CodeActivity"
  version: "0.1.0"

server:
  host: "0.0.0.0"
  port: 10000
  debug: true

web:
  port: 10001

event_types:
  - keystroke
  - file_save
  - file_open
  - terminal_command

extension:
  debounce_time: 10
  max_debounce_time: 60
  debounces_before_push: 3
  tracked_extensions:
    - .c
    - .cpp
    - .cc
    - .h
    - .hpp
    - .hh
  tracked_filenames:
    - Makefile
    - makefile
